### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by jnareb** [yohm/rb_call#2]
Under what license is that code published?

It is not packaged into a Python package that you can simply install, so if I want to use it, I would have to embed it (copy the code to my project).

**Comment by yohm** [comment]
It is published under the MIT license. Please find the license in the README.
https://github.com/yohm/rb_call?tab=readme-ov-file#license

I wish to make it a Python package, but I don't know how. Your PR would be appreciated 😄

**Comment by jnareb** [comment]
> It is published under the MIT license. Please find the license in the README. https://github.com/yohm/rb_call?tab=readme-ov-file#license

Thank you very much for the answer.

By the way, if there is appropriate `LICENSE` file added in the repository, GitHub will show the license in project metadata.

**Comment by jnareb** [comment]
> By the way, if there is appropriate `LICENSE` file added in the repository, GitHub will show the license in project metadata.

See PR #3
